-- Complete Appointment Booking System Migration
-- Run this in Supabase SQL Editor to set up the complete appointment booking system

-- ====================
-- 1. ENSURE PAYMENT TABLES EXIST
-- ====================

-- Add missing columns to appointments table if they don't exist
DO $$ 
BEGIN
    -- Add cancellation fields
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='appointments' AND column_name='cancellation_reason') THEN
        ALTER TABLE appointments ADD COLUMN cancellation_reason TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='appointments' AND column_name='cancellation_fee') THEN
        ALTER TABLE appointments ADD COLUMN cancellation_fee DECIMAL(10,2) DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='appointments' AND column_name='cancelled_at') THEN
        ALTER TABLE appointments ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
    END IF;
END $$;

-- Ensure payments table exists with all necessary columns
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT REFERENCES appointments(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  status payment_status DEFAULT 'PENDING',
  payment_method TEXT,
  transaction_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create payment_methods table for storing user payment info
CREATE TABLE IF NOT EXISTS payment_methods (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'card', 'paypal', etc.
  last_four TEXT,
  is_default BOOLEAN DEFAULT false,
  provider TEXT, -- 'stripe', 'paypal', etc.
  provider_payment_method_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ====================
-- 2. ENSURE THERAPIST AVAILABILITY TABLE EXISTS
-- ====================

CREATE TABLE IF NOT EXISTS therapist_availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  therapist_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  day_of_week INTEGER CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ====================
-- 3. ENSURE THERAPIST-SERVICES RELATIONSHIP EXISTS
-- ====================

-- Check if services or therapies table exists and create appropriate link table
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='therapies') THEN
    -- Use therapies table
    CREATE TABLE IF NOT EXISTS therapist_services (
      therapist_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
      service_id BIGINT REFERENCES therapies(id) ON DELETE CASCADE,
      price DECIMAL(10,2),
      PRIMARY KEY (therapist_id, service_id)
    );
  ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='services') THEN
    -- Use services table
    CREATE TABLE IF NOT EXISTS therapist_services (
      therapist_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
      service_id BIGINT REFERENCES services(id) ON DELETE CASCADE,
      price DECIMAL(10,2),
      PRIMARY KEY (therapist_id, service_id)
    );
  ELSE
    RAISE NOTICE 'Neither therapies nor services table exists. Please create one first.';
  END IF;
END $$;

-- ====================
-- 4. ENSURE NOTIFICATIONS TABLE EXISTS
-- ====================

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  read BOOLEAN DEFAULT false,
  data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create testimonials table for therapy reviews
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  therapy_id BIGINT NOT NULL,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add foreign key for therapy_id dynamically based on table existence
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='therapies') THEN
    ALTER TABLE testimonials 
    ADD CONSTRAINT IF NOT EXISTS fk_testimonials_therapy 
    FOREIGN KEY (therapy_id) REFERENCES therapies(id) ON DELETE CASCADE;
  ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='services') THEN
    ALTER TABLE testimonials 
    ADD CONSTRAINT IF NOT EXISTS fk_testimonials_therapy 
    FOREIGN KEY (therapy_id) REFERENCES services(id) ON DELETE CASCADE;
  END IF;
END $$;

-- ====================
-- 5. CREATE INDEXES FOR PERFORMANCE
-- ====================

CREATE INDEX IF NOT EXISTS idx_therapist_availability_therapist ON therapist_availability(therapist_id);
CREATE INDEX IF NOT EXISTS idx_therapist_availability_day ON therapist_availability(day_of_week);
CREATE INDEX IF NOT EXISTS idx_therapist_services_therapist ON therapist_services(therapist_id);
CREATE INDEX IF NOT EXISTS idx_therapist_services_service ON therapist_services(service_id);
CREATE INDEX IF NOT EXISTS idx_payments_appointment ON payments(appointment_id);
CREATE INDEX IF NOT EXISTS idx_payment_methods_user ON payment_methods(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_testimonials_therapy ON testimonials(therapy_id);
CREATE INDEX IF NOT EXISTS idx_testimonials_approved ON testimonials(is_approved);
CREATE INDEX IF NOT EXISTS idx_testimonials_user ON testimonials(user_id);
-- Only create index if status column exists
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns 
             WHERE table_name='appointments' AND column_name='status') THEN
    CREATE INDEX IF NOT EXISTS idx_appointments_scheduled_status ON appointments(scheduled_at, status);
  END IF;
END $$;

-- ====================
-- 6. SETUP ROW LEVEL SECURITY
-- ====================

-- Enable RLS on all tables
ALTER TABLE therapist_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE therapist_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;

-- Therapist Availability Policies
DROP POLICY IF EXISTS "Therapists can manage their own availability" ON therapist_availability;
CREATE POLICY "Therapists can manage their own availability" 
ON therapist_availability 
FOR ALL 
USING (auth.uid() = therapist_id);

DROP POLICY IF EXISTS "Anyone can view therapist availability" ON therapist_availability;
CREATE POLICY "Anyone can view therapist availability" 
ON therapist_availability 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Admins can manage all availability" ON therapist_availability;
CREATE POLICY "Admins can manage all availability" 
ON therapist_availability 
FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() AND role = 'ADMIN'
  )
);

-- Therapist Services Policies
DROP POLICY IF EXISTS "Anyone can view therapist services" ON therapist_services;
CREATE POLICY "Anyone can view therapist services" 
ON therapist_services 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Therapists can manage their own services" ON therapist_services;
CREATE POLICY "Therapists can manage their own services" 
ON therapist_services 
FOR ALL 
USING (auth.uid() = therapist_id);

DROP POLICY IF EXISTS "Admins can manage all therapist services" ON therapist_services;
CREATE POLICY "Admins can manage all therapist services" 
ON therapist_services 
FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() AND role = 'ADMIN'
  )
);

-- Payment Methods Policies
DROP POLICY IF EXISTS "Users can manage their own payment methods" ON payment_methods;
CREATE POLICY "Users can manage their own payment methods" 
ON payment_methods 
FOR ALL 
USING (auth.uid() = user_id);

-- Notifications Policies
DROP POLICY IF EXISTS "Users can view their own notifications" ON notifications;
CREATE POLICY "Users can view their own notifications" 
ON notifications 
FOR SELECT 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "System can create notifications" ON notifications;
CREATE POLICY "System can create notifications" 
ON notifications 
FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications" 
ON notifications 
FOR UPDATE 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own notifications" ON notifications;
CREATE POLICY "Users can delete their own notifications" 
ON notifications 
FOR DELETE 
USING (auth.uid() = user_id);

-- Testimonials Policies
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view approved testimonials" ON testimonials;
CREATE POLICY "Anyone can view approved testimonials" 
ON testimonials 
FOR SELECT 
USING (is_approved = true OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Authenticated users can create testimonials" ON testimonials;
CREATE POLICY "Authenticated users can create testimonials" 
ON testimonials 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own testimonials" ON testimonials;
CREATE POLICY "Users can update their own testimonials" 
ON testimonials 
FOR UPDATE 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own testimonials" ON testimonials;
CREATE POLICY "Users can delete their own testimonials" 
ON testimonials 
FOR DELETE 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all testimonials" ON testimonials;
CREATE POLICY "Admins can manage all testimonials" 
ON testimonials 
FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() AND role = 'ADMIN'
  )
);

-- ====================
-- 7. CREATE TRIGGERS FOR UPDATED_AT
-- ====================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_payments_updated_at ON payments;
CREATE TRIGGER update_payments_updated_at 
BEFORE UPDATE ON payments 
FOR EACH ROW 
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_payment_methods_updated_at ON payment_methods;
CREATE TRIGGER update_payment_methods_updated_at 
BEFORE UPDATE ON payment_methods 
FOR EACH ROW 
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_testimonials_updated_at ON testimonials;
CREATE TRIGGER update_testimonials_updated_at 
BEFORE UPDATE ON testimonials 
FOR EACH ROW 
EXECUTE FUNCTION update_updated_at_column();

-- ====================
-- 8. SEED SAMPLE DATA (Optional - for testing)
-- ====================

-- Insert sample therapist availability (only if none exists)
DO $$
DECLARE
  therapist_user_id UUID;
BEGIN
  -- Get first therapist
  SELECT id INTO therapist_user_id 
  FROM profiles 
  WHERE role = 'THERAPIST' 
  LIMIT 1;

  IF therapist_user_id IS NOT NULL THEN
    -- Check if availability already exists
    IF NOT EXISTS (
      SELECT 1 FROM therapist_availability 
      WHERE therapist_id = therapist_user_id
    ) THEN
      -- Insert Monday to Friday 9am-5pm availability
      INSERT INTO therapist_availability (therapist_id, day_of_week, start_time, end_time, is_available)
      VALUES
        (therapist_user_id, 1, '09:00', '17:00', true), -- Monday
        (therapist_user_id, 2, '09:00', '17:00', true), -- Tuesday
        (therapist_user_id, 3, '09:00', '17:00', true), -- Wednesday
        (therapist_user_id, 4, '09:00', '17:00', true), -- Thursday
        (therapist_user_id, 5, '09:00', '17:00', true); -- Friday
    END IF;
  END IF;
END $$;

-- ====================
-- 9. CREATE USEFUL VIEWS
-- ====================

-- View for upcoming appointments with full details (only if status column exists)
DO $$ 
DECLARE
  therapy_table_name TEXT;
BEGIN
  -- Determine which table to use (therapies or services)
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='therapies') THEN
    therapy_table_name := 'therapies';
  ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='services') THEN
    therapy_table_name := 'services';
  ELSE
    therapy_table_name := NULL;
  END IF;

  IF therapy_table_name IS NOT NULL AND 
     EXISTS (SELECT 1 FROM information_schema.columns 
             WHERE table_name='appointments' AND column_name='status') THEN
    EXECUTE format('
      CREATE OR REPLACE VIEW upcoming_appointments AS
      SELECT 
        a.id,
        a.scheduled_at,
        a.duration_minutes,
        a.status,
        a.price,
        a.notes,
        c.id as client_id,
        c.name as client_name,
        c.email as client_email,
        t.id as therapist_id,
        t.name as therapist_name,
        t.email as therapist_email,
        s.id as service_id,
        s.name as service_name,
        p.status as payment_status,
        p.amount as payment_amount
      FROM appointments a
      LEFT JOIN profiles c ON a.client_id = c.id
      LEFT JOIN profiles t ON a.therapist_id = t.id
      LEFT JOIN %I s ON a.service_id = s.id
      LEFT JOIN payments p ON a.id = p.appointment_id
      WHERE a.scheduled_at >= NOW()
        AND a.status IN (''PENDING'', ''CONFIRMED'')
      ORDER BY a.scheduled_at ASC', therapy_table_name);
  END IF;
END $$;

-- ====================
-- 10. GRANT PERMISSIONS
-- ====================

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated;

-- ====================
-- MIGRATION COMPLETE
-- ====================

-- Verify tables exist
SELECT 
  'appointments' as table_name, COUNT(*) as row_count FROM appointments
UNION ALL
SELECT 'payments', COUNT(*) FROM payments
UNION ALL
SELECT 'therapist_availability', COUNT(*) FROM therapist_availability
UNION ALL
SELECT 'therapist_services', COUNT(*) FROM therapist_services
UNION ALL
SELECT 'notifications', COUNT(*) FROM notifications
UNION ALL
SELECT 'payment_methods', COUNT(*) FROM payment_methods;
